[supervisord]
nodaemon=true
[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/html/artisan queue:listen
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/worker.log
user=root

[program:storage-link]
command=php /var/www/html/artisan storage:link
autostart=true
autorestart=false
startsecs=0
priority=1

[program:cache-config]
command=php /var/www/html/artisan config:cache
autostart=true
autorestart=false
startsecs=0
priority=1




[program:laravel-server]
command=php artisan serve --host=0.0.0.0 --port=8000
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/server.log
