[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm -F
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true

[program:storage-link]
command=php /var/www/html/artisan storage:link
autostart=true
autorestart=false
startsecs=0
priority=1

[program:cache-config]
command=php /var/www/html/artisan config:cache
autostart=true
autorestart=false
startsecs=0
priority=1