name: Deploy to Vercel

on:
  push:
    branches:
      - feature/paypal-intergration-setup

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_pgsql, pgsql
      - name: Install OpenSSL libraries
        run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Link Project to Vercel
        run: vercel link --yes --project payment_app --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Environment Variables from Vercel
        run: vercel env pull .env --token=${{ secrets.VERCEL_TOKEN }}

      - name: Symlink of public folder
        run: |
          if [ ! -L public/storage ]; then
            php artisan storage link || echo "Symbolic link already exists or there was an error."
          else
            echo "Symbolic link already exists."
          fi
        env:
          APP_ENV: production
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Migrate DB
        run: php artisan migrate --force
        
      - name: Seeding  DB
        run: php artisan db seed --force

      - name: Deploy to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
