name: Deploy to Vercel

on:
  push:
    branches:
      - feature/paypal-intergration-setup

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: pdo, pdo_pgsql, pgsql
      - name: Install OpenSSL libraries
        run: sudo apt-get update && sudo apt-get install -y libssl-dev
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Install Composer Dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Link Project to Vercel
        run: vercel link --yes --project payment_app --token=${{ secrets.VERCEL_TOKEN }}

      - name: Pull Environment Variables from Vercel
        run: vercel env pull .env --token=${{ secrets.VERCEL_TOKEN }}

      - name: Symlink of public folder
        run: |
          if [ ! -L public/storage ]; then
            php artisan storage link || echo "Failed to create symbolic link. Ensure the 'public/storage' directory exists and has the correct permissions."
          else
            echo "Symbolic link already exists."
          fi
      - name: Migrate DB
        run: php artisan migrate --force

        env:
          APP_ENV: production
          DB_CONNECTION: pgsql
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Pull latest Docker image
        run: docker pull shamimsg3/payment-app:latest

      - name: Stop existing container (if running)
        run: docker stop payment-worker || true && docker rm payment-worker || true

      - name: Run new worker container
        run: |
          docker run -d \
            --name=payment-worker \
            --restart=always \
            -e QUEUE_CONNECTION=database \
            -e POSTGRES_CONNECTION=pgsql \
            -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} \
            -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            -e POSTGRES_DATABASE=${{ secrets.POSTRGES_DATABASE }} \
            -e POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} \
            -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
            shamimsg3/payment-app:latest

      - name: List running Docker containers
        run: docker ps -a

      - name: Show worker logs
        run: docker logs payment-worker
        
